### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by allxone** [allxone/SEBC#1]

**Comment by allxone** [comment]
# Mysql

choosed plan B

# Host roles:
- ip-172-31-31-81.ec2.internal (MySql master, Cloudera Manager, Zookeeper, Hadoop Masters and Edge roles)
- ip-172-31-31-82.ec2.internal (MySql worker, Zookeeper, Hadoop Worker)
- ip-172-31-31-83.ec2.internal (Zookeeper, Hadoop Worker)
- ip-172-31-31-84.ec2.internal (Hadoop Worker)
- ip-172-31-31-85.ec2.internal (Hadoop Worker)

# Out of ordinary

Suppressed warning for Nn/Snn/Dn/Nm data disk with less than 10GB free (data disk mounted in /data/disk1 is only 8GB)

**Comment by mfernest** [comment]
I'll evaluate this lab as soon as I have passed through all the repositories one time.

**Comment by mfernest** [comment]
Excellent work, including the bonus lab. 🏆
