### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by allxone** [allxone/SEBC#2]

**Comment by allxone** [comment]
Added replication by finding a student repository on GitHub (goelph) updated 1 hour ago. I added his CM as a peer and added replication scehdule. Sorry but I don't know who goelph is but I was not able to find a partner in person to setup the replication.

**Comment by allxone** [comment]
I finally found a replication partner (rakrawat) and I am setting up replication with him

**Comment by allxone** [comment]
I finally found a replication partner (rakrawat) and I am setting up replication with him

**Comment by allxone** [comment]
Successfully replicated cross-cluster by inserting remote cluster hostnames in my /etc/hosts

**Comment by allxone** [comment]
just one question about Hive replication. Are the related Sentry grants replicated too or I have to repeat them on the target cluster?

**Comment by mikeridley** [comment]
BDR, unfortunately, does not replicate the Sentry database.  This is a known opportunity for improvement. :-)  As of now you have to replicate it independently.

**Comment by mfernest** [comment]
👍
